version: '2.1'

services:
  # image for build artifacts
  inasafe-fba:
    image: inasafe/inasafe-fba
    build:
      dockerfile: deployment/docker/Dockerfile
      context: ../
    command: bash -c "nginx -g 'daemon off;' || tail -f /dev/null"
    environment:
      REPO_ROOT: ${REPO_ROOT}
      POSTGREST_SERVER: ${POSTGREST_SERVER:-postgrest.fbf.test:3000}
      SWAGGER_SERVER: ${SWAGGER_SERVER:-swagger.fbf.test:3080}
      GEOSERVER_SERVER: ${GEOSERVER_SERVER:-geoserver.fbf.test:8000}
      MAPSERVER_SERVER: ${MAPSERVER_SERVER:-mapserver.fbf.test:8000}
      FBA_SERVER: ${FBA_SERVER:-fba.fbf.test:8080}
      GEOSERVER_BASE_URL: ${GEOSERVER_BASE_URL}
      MAPSERVER_BASE_URL: ${MAPSERVER_BASE_URL}
      POSTGREST_BASE_URL: ${POSTGREST_BASE_URL}
      MAPSERVER_PUBLIC_WMS_URL: ${MAPSERVER_PUBLIC_WMS_URL}
      FRONTEND_PUBLIC_WMS_URL: ${FRONTEND_PUBLIC_WMS_URL}
      FRONTEND_PUBLIC_OWS_URL: ${FRONTEND_PUBLIC_OWS_URL}
      FRONTEND_FBA_PROXY_URL: ${FRONTEND_FBA_PROXY_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
